// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Database.Context;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260718221308_FixTotalXPDefault")]
    partial class FixTotalXPDefault
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()")
                        .HasComment("UTC timestamp of when the group was created");

                    b.Property<string>("InvitationCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength()
                        .HasComment("Short unique code shared with students to join the group");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasComment("Inactive groups are hidden but their data is preserved");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Display name of the group, e.g. '11th Grade A'");

                    b.Property<int>("ProfessorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InvitationCode")
                        .IsUnique()
                        .HasDatabaseName("IX_Groups_InvitationCode");

                    b.HasIndex("ProfessorId", "IsActive")
                        .HasDatabaseName("IX_Groups_ProfessorId_IsActive");

                    b.ToTable("Groups", (string)null);
                });

            modelBuilder.Entity("backend.Models.Professor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasComment("Used for login. Must be unique across all professors");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Full name of the professor");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasComment("Bcrypt hash of the password. Never store plain text passwords");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Professors_Email");

                    b.ToTable("Professors", (string)null);
                });

            modelBuilder.Entity("backend.Models.QuestCompletion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CompletedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()")
                        .HasComment("UTC timestamp of when the student completed the quest");

                    b.Property<string>("QuestId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("References the quest ID defined in the frontend JSON, e.g. 'quest-1'");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("XpEarned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasComment("Total XP awarded to the student for completing this quest");

                    b.HasKey("Id");

                    b.HasIndex("StudentId", "QuestId")
                        .IsUnique()
                        .HasDatabaseName("IX_QuestCompletions_StudentId_QuestId");

                    b.ToTable("QuestCompletions", (string)null);
                });

            modelBuilder.Entity("backend.Models.SpeakingSubmission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AudioUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("Permanent Cloudinary URL to the recorded audio file");

                    b.Property<int?>("BonusXP")
                        .HasColumnType("int")
                        .HasComment("Extra XP assigned by the professor after reviewing. Null if not yet reviewed");

                    b.Property<string>("OptionChosen")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("The sentence the student chose to record, e.g. option A, B or C from the quest JSON");

                    b.Property<string>("ProfessorFeedback")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasComment("Optional written feedback from the professor. Null if not yet reviewed");

                    b.Property<string>("QuestId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("References the quest ID defined in the frontend JSON, e.g. 'quest-1'");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2")
                        .HasComment("UTC timestamp of when the professor reviewed the submission. Null if pending");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmittedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()")
                        .HasComment("UTC timestamp of when the student submitted the recording");

                    b.HasKey("Id");

                    b.HasIndex("ReviewedAt")
                        .HasDatabaseName("IX_SpeakingSubmissions_ReviewedAt");

                    b.HasIndex("StudentId", "QuestId")
                        .HasDatabaseName("IX_SpeakingSubmissions_StudentId_QuestId");

                    b.ToTable("SpeakingSubmissions", (string)null);
                });

            modelBuilder.Entity("backend.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasComment("Used for login. Must be unique across all students");

                    b.Property<int?>("GroupId")
                        .HasColumnType("int")
                        .HasComment("The group the student belongs to. Null if not yet assigned");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Full name of the student");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasComment("Bcrypt hash of the password. Never store plain text passwords");

                    b.Property<int>("TotalXP")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasComment("Accumulated experience points across all quests and submissions");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Students_Email");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("IX_Students_GroupId");

                    b.ToTable("Students", (string)null);
                });

            modelBuilder.Entity("backend.Models.Group", b =>
                {
                    b.HasOne("backend.Models.Professor", "Professor")
                        .WithMany("Groups")
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Professor");
                });

            modelBuilder.Entity("backend.Models.QuestCompletion", b =>
                {
                    b.HasOne("backend.Models.Student", "Student")
                        .WithMany("QuestCompletions")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("backend.Models.SpeakingSubmission", b =>
                {
                    b.HasOne("backend.Models.Student", "Student")
                        .WithMany("SpeakingSubmissions")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("backend.Models.Student", b =>
                {
                    b.HasOne("backend.Models.Group", "Group")
                        .WithMany("Students")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Group");
                });

            modelBuilder.Entity("backend.Models.Group", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("backend.Models.Professor", b =>
                {
                    b.Navigation("Groups");
                });

            modelBuilder.Entity("backend.Models.Student", b =>
                {
                    b.Navigation("QuestCompletions");

                    b.Navigation("SpeakingSubmissions");
                });
#pragma warning restore 612, 618
        }
    }
}
