namespace backend.Models;

/// <summary>
/// Represents a group in the system, which is managed by a professor and contains multiple students. Contains properties for identification, invitation code for joining, active status, and timestamps for creation. Also includes navigation properties to the professor managing the group and the students belonging to the group.
/// </summary>
public class Group
{
    // Unique identifier for the group, generated by the database.
    public int Id { get; set; }

    // Name of the group, required for identification and display purposes.
    public string Name { get; set; } = string.Empty;

    // Invitation code for students to join the group, ensuring secure access and management of group membership.
    public string InvitationCode { get; set; } = string.Empty;

    // Indicates whether the group is currently active, allowing for soft deletion or temporary deactivation without removing the group from the database.
    public bool IsActive { get; set; } = true;

    // Timestamp for when the group was created, useful for tracking and auditing purposes.
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    // Foreign key referencing the professor who manages the group, establishing a relationship between the group and its managing professor.
    public int ProfessorId { get; set; }

    // Navigation property representing the professor who manages the group. This allows for easy access to related professor data when querying the group.
    public Professor Professor { get; set; } = null!;

    // Navigation property representing the students belonging to the group. This allows for easy access to related student data when querying the group.
    public List<Student> Students { get; set; } = new();
}