namespace backend.Models;
/// <summary>
/// Represents a professor in the system, responsible for managing groups and //students. Contains properties for identification, contact information, and authentication. Also includes a navigation property to the groups they manage.
/// </summary>
public class Professor
{
    //Unique identifier for the professor, generated by the database.
    public int Id { get; set; }

    // Name of the professor, required for identification and display purposes.
    public string Name { get; set; } = string.Empty;

    // Email address of the professor, used for contact and authentication purposes.
    public string Email { get; set; } = string.Empty;
    
    // Hashed password for authentication, ensuring secure storage of credentials.
    public string PasswordHash { get; set; } = string.Empty;

    // Navigation property representing the groups managed by the professor. This allows for easy access to related group data when querying the professor.
    public List<Group> Groups { get; set; } = new();
}