namespace backend.Models;

/// <summary>
/// Represents a quest completion by a student, containing properties for identification, the quest completed, experience points earned, and the timestamp of completion. Also includes navigation properties to the student who completed the quest. This model allows for tracking the progress and achievements of students within the system.
/// </summary>
public class QuestCompletion
{
    // Unique identifier for the quest completion, generated by the database.
    public int Id { get; set; }

    // Identifier for the quest that was completed, which can be used to link to quest details and track specific achievements.
    public string QuestId { get; set; } = string.Empty;  

    // Experience points earned by the student for completing the quest, which can be used for gamification and tracking progress within the system.
    public int XpEarned { get; set; }

    // Timestamp for when the quest was completed, useful for tracking and auditing purposes.
    public DateTime CompletedAt { get; set; } = DateTime.UtcNow;

    // Foreign key referencing the student who completed the quest, establishing a relationship between the quest completion and the student.
    public int StudentId { get; set; }

    // Navigation property representing the student who completed the quest. This allows for easy access to related student data when querying the quest completion.
    public Student Student { get; set; } = null!;
}