namespace backend.Models;
/// <summary>
/// Represents a speaking submission by a student for a specific quest, containing properties for identification, the quest associated with the submission, the URL of the audio recording, the option chosen by the student, any bonus experience points awarded, feedback from the professor, and timestamps for when the submission was made and reviewed. Also includes navigation properties to the student who made the submission. This model allows for tracking and managing speaking submissions within the system.
/// </summary>
public class SpeakingSubmission
{
    // Unique identifier for the speaking submission, generated by the database.
    public int Id { get; set; }

    // Identifier for the quest associated with the speaking submission, which can be used to link to quest details and track specific submissions.
    public string QuestId { get; set; } = string.Empty;  

    // URL of the audio recording submitted by the student, which can be used for playback and evaluation of the submission.
    public string AudioUrl { get; set; } = string.Empty;

    // Option chosen by the student for the speaking submission, used so the professor knows wich sentence the student is trying to say
    public string OptionChosen { get; set; } = string.Empty;

    // Bonus experience points awarded by the professor for the speaking submission, which can be used for gamification and tracking progress within the system. Null if not reviewed yet or if no bonus XP is awarded.
    public int? BonusXP { get; set; }

    // Feedback from the professor regarding the speaking submission, which can be used for providing constructive criticism and guidance to the student. Null if not reviewed yet.                    
    public string? ProfessorFeedback { get; set; }        

    // Timestamp for when the speaking submission was made, useful for tracking and auditing purposes.
    public DateTime SubmittedAt { get; set; } = DateTime.UtcNow;

    // Timestamp for when the speaking submission was reviewed by the professor, useful for tracking and auditing purposes. Null if not reviewed yet.
    public DateTime? ReviewedAt { get; set; }             

    // Foreign key referencing the student who made the speaking submission, establishing a relationship between the speaking submission and the student.
    public int StudentId { get; set; }

    // Navigation property representing the student who made the speaking submission. This allows for easy access to related student data when querying the speaking submission.
    public Student Student { get; set; } = null!;
}