namespace backend.Models;

/// <summary>
/// Represents a student in the system, who can belong to a group managed by a professor. Contains properties for identification, contact information, authentication, and total experience points (XP). Also includes navigation properties to the group they belong to, their quest completions, and their speaking submissions.
/// </summary>
public class Student
{ 
    // Unique identifier for the student, generated by the database.
    public int Id { get; set; }

    // Name of the student, required for identification and display purposes.
    public string Name { get; set; } = string.Empty;

    // Email address of the student, used for contact and authentication purposes.
    public string Email { get; set; } = string.Empty;

    // Hashed password for authentication, ensuring secure storage of credentials.
    public string PasswordHash { get; set; } = string.Empty;

    // Total experience points (XP) accumulated by the student, which can be used for gamification and tracking progress within the system.
    public int TotalXP { get; set; } = 0;

    // Foreign key referencing the group the student belongs to, establishing a relationship between the student and their group.
    public int? GroupId { get; set; }  
    
    // Navigation property representing the group the student belongs to. This allows for easy access to related group data when querying the student.
    public Group? Group { get; set; }

    // Navigation property representing the quest completions of the student. This allows for easy access to related quest completion data when querying the student.
    public List<QuestCompletion> QuestCompletions { get; set; } = new();

    // Navigation property representing the speaking submissions of the student. This allows for easy access to related speaking submission data when querying the student.
    public List<SpeakingSubmission> SpeakingSubmissions { get; set; } = new();
}